const testRoute = [
  {
    "actionid": "1",
    "actionpid": "0",
    "id": "1",
    "name": "管理视图",
    "pId": "0",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "管理视图",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcicon": "chart",
    "vcmodel": "内部链接",
    "vcpid": "1",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "/managementView"
  },
  {
    "actionid": "101",
    "actionpid": "1",
    "id": "101",
    "name": "管理视图",
    "pId": "1",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "管理视图",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "101",
    "vcremark": "views/managementView/management",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "management"
  },
  {
    "actionid": "102",
    "actionpid": "1",
    "id": "102",
    "name": "投资经理视图",
    "pId": "1",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "投资经理视图",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "102",
    "vcremark": "views/managementView/investmentManager",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "investmentManager"
  },
  {
    "actionid": "103",
    "actionpid": "1",
    "id": "103",
    "name": "投委会",
    "pId": "1",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "投委会",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "103",
    "vcremark": "views/managementView/investmentCommittee",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "investmentCommittee"
  },
  {
    "actionid": "104",
    "actionpid": "1",
    "id": "104",
    "name": "我的绩效详情",
    "pId": "1",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "我的绩效详情",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "104",
    "vcremark": "views/managementView/investmentManagerPerson",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "investmentManagerPerson"
  },
  {
    "actionid": "2",
    "actionpid": "0",
    "id": "2",
    "name": "绩效归因",
    "pId": "0",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "绩效归因",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcicon": "eye-open",
    "vcmodel": "内部链接",
    "vcpid": "2",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "/performance"
  },
  {
    "actionid": "201",
    "actionpid": "2",
    "id": "201",
    "name": "组合绩效情况总览",
    "pId": "2",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合绩效情况总览",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "201",
    "vcremark": "views/performance/groupPandect",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "perGroupPandect"
  },
  {
    "actionid": "202",
    "actionpid": "2",
    "id": "202",
    "name": "组合绩效详情",
    "pId": "2",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合绩效详情",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "202",
    "vcremark": "views/performance/groupDetails",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "perGroupDetails"
  },
  {
    "actionid": "203",
    "actionpid": "2",
    "id": "203",
    "name": "组合收益对比分析",
    "pId": "2",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合收益对比分析",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "203",
    "vcremark": "views/performance/groupEarnings",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "perGroupEarnings"
  },
  {
    "actionid": "204",
    "actionpid": "2",
    "id": "204",
    "name": "组合绩效归因",
    "pId": "2",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合绩效归因",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "204",
    "vcremark": "views/performance/groupAscribe",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "perGroupAscribe"
  },
  {
    "actionid": "20401",
    "actionpid": "204",
    "id": "20401",
    "name": "资产配置归因",
    "pId": "204",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "资产配置归因",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "20401",
    "vcremark": "views/performance/ascribe/groupPropertyAscribe",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "perGroupPropertyAscribe"
  },
  {
    "actionid": "20402",
    "actionpid": "204",
    "id": "20402",
    "name": "Brinson归因",
    "pId": "204",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "Brinson归因",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "20402",
    "vcremark": "views/performance/ascribe/groupBrinsonAscribe",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "perGroupBrinsonAscribe"
  },
  {
    "actionid": "20403",
    "actionpid": "204",
    "id": "20403",
    "name": "Campisi归因",
    "pId": "204",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "Campisi归因",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "20403",
    "vcremark": "views/performance/ascribe/groupCampisiAscribe",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "perGroupCampisiAscribe"
  },
  {
    "actionid": "3",
    "actionpid": "0",
    "id": "3",
    "name": "资产",
    "pId": "0",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "资产",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcicon": "money02",
    "vcmodel": "内部链接",
    "vcpid": "3",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "/property"
  },
  {
    "actionid": "301",
    "actionpid": "3",
    "id": "301",
    "name": "组合资产总览",
    "pId": "3",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合资产总览",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "301",
    "vcremark": "views/property/groupPandect",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupPandect"
  },
  {
    "actionid": "302",
    "actionpid": "3",
    "id": "302",
    "name": "组合资产详情",
    "pId": "3",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合资产详情",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "302",
    "vcremark": "views/property/groupDetails",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupDetails"
  },
  {
    "actionid": "303",
    "actionpid": "3",
    "id": "303",
    "name": "资产配置",
    "pId": "3",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "资产配置",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "303",
    "vcremark": "views/property/inquire/groupDeployInquire",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupDeployInquire"
  },
  {
    "actionid": "304",
    "actionpid": "3",
    "id": "304",
    "name": "组合明细查询",
    "pId": "3",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合明细查询",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "304",
    "vcremark": "views/property/groupInquire",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupInquire"
  },
  {
    "actionid": "30401",
    "actionpid": "304",
    "id": "30401",
    "name": "持仓查询",
    "pId": "304",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "持仓查询",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "30401",
    "vcremark": "views/property/inquire/groupPositionInquire",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupPositionInquire"
  },
  {
    "actionid": "30403",
    "actionpid": "304",
    "id": "30403",
    "name": "盈亏变动",
    "pId": "304",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "盈亏变动",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "30403",
    "vcremark": "views/property/inquire/groupProfitInquire",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupProfitInquire"
  },
  {
    "actionid": "30404",
    "actionpid": "304",
    "id": "30404",
    "name": "重合度",
    "pId": "304",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "重合度",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "30404",
    "vcremark": "views/property/inquire/groupCoincideInquire",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupCoincideInquire"
  },
  {
    "actionid": "30405",
    "actionpid": "304",
    "id": "30405",
    "name": "交易查询",
    "pId": "304",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "交易查询",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "30405",
    "vcremark": "views/property/inquire/groupDealInquire",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupDealInquire"
  },
  {
    "actionid": "3030501",
    "actionpid": "30405",
    "id": "3030501",
    "name": "个券变动流水查询",
    "pId": "30405",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "个券变动流水查询",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "3040501",
    "vcremark": "views/property/inquire/deal/groupCouponInquire",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupCouponInquire"
  },
  {
    "actionid": "3030502",
    "actionpid": "30405",
    "id": "3030502",
    "name": "资金流入流出",
    "pId": "30405",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "资金流入流出",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "3040502",
    "vcremark": "views/property/inquire/deal/groupChangeInquire",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupChangeInquire"
  },
  {
    "actionid": "30406",
    "actionpid": "304",
    "id": "30406",
    "name": "费用查询",
    "pId": "304",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "费用查询",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "30406",
    "vcremark": "views/property/inquire/groupCostInquire",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupCostInquire"
  },
  {
    "actionid": "30407",
    "actionpid": "304",
    "id": "30407",
    "name": "持仓事件查询",
    "pId": "304",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "持仓事件查询",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "30407",
    "vcremark": "views/property/inquire/groupCabinInquire",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "proGroupCabinInquire"
  },
  {
    "actionid": "4",
    "actionpid": "0",
    "id": "4",
    "name": "风险管理",
    "pId": "0",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "风险管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcicon": "lock",
    "vcmodel": "内部链接",
    "vcpid": "4",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "/risk"
  },
  {
    "actionid": "402",
    "actionpid": "4",
    "id": "402",
    "name": "风险预警",
    "pId": "4",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "风险预警",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "402",
    "vcremark": "views/risk/riskwarn",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "riskwarn"
  },
  {
    "actionid": "40201",
    "actionpid": "402",
    "id": "40201",
    "name": "权益中枢偏离度监控",
    "pId": "402",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "权益中枢偏离度监控",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "40201",
    "vcremark": "views/risk/warn/riskwarnInvest",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "riskwarnInvest"
  },
  {
    "actionid": "403",
    "actionpid": "4",
    "id": "403",
    "name": "风险分析",
    "pId": "4",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "风险分析",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "403",
    "vcremark": "views/risk/riskAnalyze",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "riskAnalyze"
  },
  {
    "actionid": "40301",
    "actionpid": "403",
    "id": "40301",
    "name": "流动性风险分析",
    "pId": "403",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "流动性风险分析",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "40301",
    "vcremark": "views/risk/analyze/riskAnalyzeFlow",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "riskAnalyzeFlow"
  },
  {
    "actionid": "40302",
    "actionpid": "403",
    "id": "40302",
    "name": "集中度分析",
    "pId": "403",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "集中度分析",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "40302",
    "vcremark": "views/risk/analyze/riskAnalyzeFocus",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "riskAnalyzeFocus"
  },
  {
    "actionid": "404",
    "actionpid": "4",
    "id": "404",
    "name": "股票池管理",
    "pId": "4",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "股票池管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "404",
    "vcremark": "views/risk/riskStock",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "riskStock"
  },
  {
    "actionid": "5",
    "actionpid": "0",
    "id": "5",
    "name": "报告",
    "pId": "0",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "报告",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcicon": "table",
    "vcmodel": "内部链接",
    "vcpid": "5",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "/report"
  },
  {
    "actionid": "501",
    "actionpid": "5",
    "id": "501",
    "name": "含权组合绩效归因报告",
    "pId": "5",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "含权组合绩效归因报告",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "501",
    "vcremark": "views/report/reportContain",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "reportContain"
  },
  {
    "actionid": "502",
    "actionpid": "5",
    "id": "502",
    "name": "固收组合绩效归因报告",
    "pId": "5",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "固收组合绩效归因报告",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "502",
    "vcremark": "views/report/reportSolid",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "reportSolid"
  },
  {
    "actionid": "503",
    "actionpid": "5",
    "id": "503",
    "name": "股票型组合绩效归因报告",
    "pId": "5",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "股票型组合绩效归因报告",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "503",
    "vcremark": "views/report/reportStock",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "reportStock"
  },
  {
    "actionid": "6",
    "actionpid": "0",
    "id": "6",
    "name": "数据管理",
    "pId": "0",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "数据管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcicon": "clipboard",
    "vcmodel": "内部链接",
    "vcpid": "6",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "/dataManage"
  },
  {
    "actionid": "601",
    "actionpid": "6",
    "id": "601",
    "name": "组合信息查询",
    "pId": "6",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合信息查询",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "601",
    "vcremark": "views/dataManage/dataManageProduct",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "dataManageProduct"
  },
  {
    "actionid": "602",
    "actionpid": "6",
    "id": "602",
    "name": "基准信息维护",
    "pId": "6",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "基准信息维护",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "602",
    "vcremark": "views/dataManage/dataManageFile",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "dataManageFile"
  },
  {
    "actionid": "604",
    "actionpid": "6",
    "id": "604",
    "name": "组合绩效总览信息维护",
    "pId": "6",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合绩效总览信息维护",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "604",
    "vcremark": "views/dataManage/dataManageRanking",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "dataManageRanking"
  },
  {
    "actionid": "605",
    "actionpid": "6",
    "id": "605",
    "name": "工作组信息维护",
    "pId": "6",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "工作组信息维护",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "605",
    "vcremark": "views/dataManage/dataManageGroupWork",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "dataManageGroupWork"
  },
  {
    "actionid": "606",
    "actionpid": "6",
    "id": "606",
    "name": "组合与基准映射关系维护",
    "pId": "6",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合与基准映射关系维护",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "606",
    "vcremark": "views/dataManage/dataManageStandard",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "dataManageStandard"
  },
  {
    "actionid": "607",
    "actionpid": "6",
    "id": "607",
    "name": "投委会信息维护",
    "pId": "6",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "投委会信息维护",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "607",
    "vcremark": "views/dataManage/dataManageFileSearch",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "dataManageFileSearch"
  },
  {
    "actionid": "608",
    "actionpid": "6",
    "id": "608",
    "name": "组合辅助信息维护",
    "pId": "6",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "组合辅助信息维护",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "608",
    "vcremark": "views/dataManage/dataManageAuxiliary",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "dataManageAuxiliary"
  },
  {
    "actionid": "609",
    "actionpid": "6",
    "id": "609",
    "name": "投资经理信息维护",
    "pId": "6",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "投资经理信息维护",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "609",
    "vcremark": "views/dataManage/dataManageInvestManager",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "dataManageInvestManager"
  },
  {
    "actionid": "99",
    "actionpid": "0",
    "id": "99",
    "name": "系统管理",
    "pId": "0",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "系统管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcicon": "account",
    "vcmodel": "内部链接",
    "vcpid": "99",
    "vcstatus": "启用",
    "vcurl": "/setting"
  },
  {
    "actionid": "9900",
    "actionpid": "99",
    "id": "9900",
    "name": "部门管理",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "部门管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9900",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcurl": "rest/dept/deptList.do"
  },
  {
    "actionid": "9901",
    "actionpid": "99",
    "id": "9901",
    "name": "用户管理",
    "pId": "99",
    "vcactioncode": "MENU.YHGL",
    "vcactionname": "用户管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9901",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcurl": "rest/user/userList.do"
  },
  {
    "actionid": "9902",
    "actionpid": "99",
    "id": "9902",
    "name": "角色管理",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "角色管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9902",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcurl": "rest/role/roleList.do"
  },
  {
    "actionid": "9909",
    "actionpid": "99",
    "id": "9909",
    "name": "授权管理",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "授权管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9903",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "rest/adminPermission/userGrant.do"
  },
  {
    "actionid": "9905",
    "actionpid": "99",
    "id": "9905",
    "name": "ETL管理",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "ETL管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9905",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcurl": "rest/public/commonMenu.do?mid=9905&fundFlag=false"
  },
  {
    "actionid": "9910",
    "actionpid": "99",
    "id": "9910",
    "name": "登录日志",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "登录日志",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9910",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcurl": "rest/system/logList.do"
  },
  {
    "actionid": "9911",
    "actionpid": "99",
    "id": "9911",
    "name": "操作日志",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "操作日志",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9911",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcurl": "rest/user/operlog.do"
  },
  {
    "actionid": "9912",
    "actionpid": "99",
    "id": "9912",
    "name": "操作日志4",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "操作日志4",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9912",
    "vcremark": "views/setting/department",
    "vcstatus": "启用"
  },
  {
    "actionid": "9920",
    "actionpid": "99",
    "id": "9920",
    "name": "菜单管理",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "菜单管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9920",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcurl": "rest/menu/menumanage.do"
  },
  {
    "actionid": "9921",
    "actionpid": "99",
    "id": "9921",
    "name": "通用报告管理",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "通用报告管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9921",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "rest/public/commonMenu.do?mid=9921&fundFlag=false"
  },
  {
    "actionid": "9922",
    "actionpid": "99",
    "id": "9922",
    "name": "拖拽报告维护",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "拖拽报告维护",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9922",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "rest/dynamicReport/templateList.do"
  },
  {
    "actionid": "9923",
    "actionpid": "99",
    "id": "9923",
    "name": "Excel报表下载",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "Excel报表下载",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9923",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "rest/deploy/deployListAdd.do"
  },
  {
    "actionid": "9924",
    "actionpid": "99",
    "id": "9924",
    "name": "字典管理",
    "pId": "99",
    "vcactioncode": "MENU.PORTAL",
    "vcactionname": "字典管理",
    "vcactiontype": "PAGE.PERMISSION.TYPE.MU",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9924",
    "vcremark": "views/setting/department",
    "vcstatus": "启用",
    "vcurl": "rest/edims/edimList.do"
  },
  {
    "actionid": "9999999",
    "actionpid": "-1",
    "id": "9999999",
    "name": "测试无状态权限",
    "pId": "-1",
    "vcactioncode": "A9999999",
    "vcactionname": "测试无状态权限",
    "vcactiontype": "source",
    "vcgroup": "本系统",
    "vcmodel": "内部链接",
    "vcpid": "9999999",
    "vcstatus": "启用",
    "vcteam": "0",
    "vcurl": "rest/token/userInfo.do"
  }
]

export default testRoute
